### PR TITLE
updating catalog.json for candidate-v1.0 channel

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
Commenting out v1.0.2 as it is a breaking change
cc @lance

### CODE REVIEW

**Comment by lance** [comment]
How is it a breaking change?

**Comment by Gregory-Pereira** [comment]
> How is it a breaking change?

This is described here https://github.com/securesign/fbc/pull/12#issuecomment-2150699134. Also:
```
opm alpha render-template basic ./graph.yaml > catalog/rhtas-operator/catalog.json
git diff
+{
+    "schema": "olm.bundle",
+    "name": "rhtas-operator.v1.0.1",
+    "package": "rhtas-operator",
+    "image": "quay.io/redhat-user-workloads/rhtas-tenant/operator/rhtas-operator-bundle:7b3aff508e3b7a3b13af7fe55ff78fce9d46ff70",
+    "properties": [
+        {
+            "type": "olm.gvk",
+            "value": {
+                "group": "rhtas.redhat.com",
+                "kind": "CTlog",
+                "version": "v1alpha1"
+            }
         },
...
```
What this shows is that opm looks up the bundle image and grabs the manifests inside of it. That image that we think is v1.0.2, the code references inside of it for the CSV and other manifests actually point to v1.0.1 so it gerenates 2 bundles both with the same name which would cause collisions.

**Comment by lance** [comment]
OK - does this PR supercede https://github.com/securesign/fbc/pull/12#issuecomment-2150699134

**Comment by Gregory-Pereira** [comment]
Yes I can either close this and remake my changes on #12 or we merge this one

**Comment by Gregory-Pereira** [comment]
To be clear, this is not to mean that we cannot have use candidates, it just means we have to make sure the CSV and version references are updated.

**Comment by Gregory-Pereira** [comment]
Going to close this, moving to #21 now that the image itself has been updated.

**Pull request closed without merging**
